version: 0.2

phases:
  install:
    commands: 
      - npm install -g hexo-cli
      - npm install
      - apt-get update
      - apt-get install -y awscli

  build: 
    commands:
      - cd blog && hexo generate

  post_build: 
    commands:
      - ls -la public/
      - cd public/ && aws s3 sync . s3://blog.joshlillie.com/